# Copyright 2020 Amazon.com, Inc. or its affiliates. All Rights Reserved.
AWSTemplateFormatVersion: '2010-09-09'
Description: Thia template is used to read the secrets from secretmanager and store it in s3 

Parameters:
  lambdaExecutionRoleName:
    Type: String
    Description: Lambda service execution role name.
    Default: "delegate-admin-secret-access-role"
  s3BucketName:
    Type: String
    Description: 'S3 bucket containing log files' 
    Default: 'secret-store'
  AppName:
    Type: String
    Description: Application Name
    Default: exercise-lambda
    
Resources:
  SpaBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      LifecycleConfiguration:                  
      BucketName: !Ref s3BucketName
      BucketEncryption: 
        ServerSideEncryptionConfiguration: 
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: 'AES256'
      PublicAccessBlockConfiguration:
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
        BlockPublicAcls: true               
  SPABucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      Bucket: !Ref SpaBucket
      PolicyDocument:
        Statement:
          - Sid: AllowSSLRequestsOnly
            Effect: Deny
            Principal: "*"
            Action: s3:*
            Resource:
              - !Sub 'arn:aws:s3:::${s3BucketName}/*'
            Condition:
              Bool:
                aws:SecureTransport: 'false'
  SecretStoreLambdaFunction:
    Type: AWS::Lambda::Function
    DependsOn:
      - SpaBucket
      - LambdaExecutionRole 
    Properties:
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/${lambdaExecutionRoleName}'
      Handler: index.handler
      Timeout: 10
      Tags:
       - Key: "Company"
         Value: "DXC"
      Runtime: python3.9
      MemorySize: 1024
      FunctionName: !Ref AppName
      Tracing: Active      
      Code:
        ZipFile: !Sub |
            import json
            import boto3
            import base64
            s3 = boto3.client('s3')
            import logging
            logger = logging.getLogger()
            logger.setLevel(logging.INFO)
            from botocore.exceptions import ClientError
            def handler(event, context):
                bucket = 'secret-store'
                key = 'secret.txt'
                id = None

                # Write id to S3
                s3.put_object(Body=get_secret(), Bucket=bucket, Key=key)
                return {
               'statusCode':200,
               'body': json.dumps(get_secret())
               
            }

            def get_secret():

                secret_name = "dxc-secret"
                region_name = "us-east-1"

                # Create a Secrets Manager client
                session = boto3.session.Session()
                client = session.client(
                    service_name='secretsmanager',
                    region_name=region_name
                )

                try:
                    get_secret_value_response = client.get_secret_value(
                        SecretId=secret_name
                    )
                except ClientError as e:
                    # For a list of exceptions thrown, see
                    # https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_GetSecretValue.html
                    raise e

                secret = get_secret_value_response['SecretString']

                print(secret)
                return secret



  
  LambdaExecutionRole:
    Type: AWS::IAM::Role    
    Properties:
      RoleName: !Ref lambdaExecutionRoleName    
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: BDT-Cloudwatch-Policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - cloudwatch:*
            Resource: "*"
      - PolicyName: s3-Access-Policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:*
            Resource: "*"
      - PolicyName: secretmanager-Access-Policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:            
          - Effect: Allow
            Action:
            - 'secretsmanager:UpdateSecret'
            - 'secretsmanager:GetSecretValue'
            - 'secretsmanager:DescribeSecret'
            - 'secretsmanager:ListSecrets'
            - 'secretsmanager:PutSecretValue'
            - 'secretsmanager:UpdateSecretVersionStage'
            Resource: "*"
            
            


